### ISSUE TITLE
Re-think and implement "What can we build" section

### ISSUE THREAD

**Issue by satazor** [ipfs/js.ipfs.io#156]
Follow up on #18 

- Rethink how this section should look like, current experience has some usability problems
- Discuss how we will implement the "embedded" apps, codepen or something else?

**Comment by andreforsousa** [comment]
@diasdavid Let's sync when you can about this, on the previous call you referred that you could send an initial concept/sketch for what you had in mind for this section. Thank you!

**Comment by diasdavid** [comment]
@andreforsousa pick 15 mins from my calendly. Note that my idea is still the same one I had back on the Berlin Dev Meetings in which I had a brainstorm with @marcooliveira and @hugomrdias. You probably can get the gist faster from them (given that you share the same office :))

**Comment by hugomrdias** [comment]
I can help here ping me @andreforsousa

**Comment by andreforsousa** [comment]
@diasdavid Ok, I thought it would be something different from what we've talked previously, no need for call then :) Here's the first approach on this, two versions (dark & light BGs) for desktop and mobile. Already using a snippet as example with IPFS code.

Depending on the amount of examples two be displayed on this section we might need to consider use a select box (dropdown) instead of the current 'pills' as tabs.
 

Let me know your thoughts,
thanks.

![what-can-you-build-section_dark](https://user-images.githubusercontent.com/39052705/44469052-88412300-a61e-11e8-8536-029d1c27b7ea.png)
![what-can-you-build-section_light](https://user-images.githubusercontent.com/39052705/44469053-88412300-a61e-11e8-87c2-7009c4256a8d.png)

**Comment by diasdavid** [comment]
I like where this is headed!!

**Comment by andreforsousa** [comment]
Thanks @diasdavid. Can you please confirm after which section will this go? That will imply choose the best background considering the website flow, exactly.

**Comment by diasdavid** [comment]
I say between `What people are building with it` and `What people are building with it`

**Comment by andreforsousa** [comment]
@PedroMiguelSS specs ready here:
- [Mobile](https://drive.google.com/drive/folders/1i56QGYi-aUuBo4mco9_xp-Ab_d0U24jO?usp=sharing)
- [Desktop](https://drive.google.com/drive/folders/1VsFJ35NjRnx2gAlCUaoGeArfsYAFvUDO?usp=sharing)

Thanks.
