### ISSUE TITLE
Mobile UI/UX improvements

### ISSUE THREAD

**Issue by satazor** [ipfs/js.ipfs.io#158]
The mobile experience has room for improvements. @andreforsousa will comment below on that.

- [x] Reduce copy lines in hero
- [x] "Cards" approach on projects and videos carousel
- [x] Community CTAs should be 100%

**Comment by andreforsousa** [comment]
It would be good to analyse if we can reduce the hero banner content on mobile versions, for the title; description and package info. This copy is taking a lot of vertical space and we could focus only on the crucial information to be displayed, maybe we could only understand for which break point would be good to do so.

For example, here's a suggestion for the package info:

> Current version: 0.31.4
> Latest update: 5 days ago

Could turn into one line only, something like :

> v0.31.4 | Updated 5 days ago


Regarding the section "Projects on top of IPFS", I would suggest avoid using the current carousel with arrows and keeping the platform screenshot a better solution would be accommodate everything on a card and displaying dots as a counter.
This is a more common approach since it will help the user to understand how many projects are there and will take a lot less more space considering the available real estate.
The screenshot of the platforms were dropped since they’re hard to understand on these small sizes. For these please check the following screen.

<img width="1024" alt="screen shot 2018-08-14 at 11 27 38" src="https://user-images.githubusercontent.com/39052705/44086735-66c1a70a-9fb5-11e8-8cde-f145ce0538dd.png">
 
The same criteria could be applied for "Publications & Talks" where we can reuse the card component:

<img width="501" alt="screen shot 2018-08-14 at 11 27 45" src="https://user-images.githubusercontent.com/39052705/44086763-7dd24972-9fb5-11e8-96d9-083122da7506.png">


A small adjustment to all the CTA’s for responsive version, they could be more comfortable to ‘tap’ if used with the max-width within the grid. Right now the larger copy is “IRC FREENODE”, but what will happen if there’s something even larger?


<img width="557" alt="screen shot 2018-08-14 at 11 27 50" src="https://user-images.githubusercontent.com/39052705/44086805-a7c30e10-9fb5-11e8-97d2-2a8e2cc6e434.png">

**Comment by andreforsousa** [comment]
@diasdavid Can we proceed with this? Do you approve all our suggestions? Thank you.

**Comment by diasdavid** [comment]
Thank you for the ping @andreforsousa, only managed to see this now. All LGTM!

**Comment by diasdavid** [comment]
Thank you for the ping @andreforsousa, only managed to see this now. All LGTM!
