### ISSUE TITLE
Still using js-ipfs 0.31.7 ??

### ISSUE THREAD

**Issue by daviddias** [ipfs/js.ipfs.io#207]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/1211152/48692195-79deb500-ebd5-11e8-8858-0b1e14be0738.png">

**Comment by daviddias** [comment]
Also the list of CIDs is always empty:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1211152/48692218-895dfe00-ebd5-11e8-9e1c-05422c7777b9.png">

Even after loading all the examples

**Comment by daviddias** [comment]
Also, just noticed:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/1211152/48692247-a7c3f980-ebd5-11e8-9162-30bd6bff9c9e.png">

**Comment by PedroMiguelSS** [comment]
I've talked with @vasco-santos as this is related to [`service-worker-gateway`](https://github.com/ipfs-shipyard/service-worker-gateway). He can't check it today but he will do it tomorrow. 

### About the version:
- He will bump it manually and check if everything's ok. 

### About empty CIDs list:
- I've tested it on `Chrome`, by visiting [peerpad](https://js.ipfs.io/ipfs/QmXRTzu4dUFnA1nLR7ogifE1EeY2hEsVyQNkZu4CzF6g2v) and it went well for me
<img width="1413" alt="screen shot 2018-11-19 at 10 27 45" src="https://user-images.githubusercontent.com/11461281/48701254-f4173580-ebe5-11e8-8734-a435abc40683.png">

- Although it has worked for me, @vasco-santos also said this is a known problem for him on `Firefox`. He will take a look at this problem tomorrow. 

### About repo size
- We will check what's happening with the repo size.

**Comment by vasco-santos** [comment]
So, regarding the `ipfs` version, I created a PR upgrading the dependencies [ipfs-shipyard/service-worker-gateway#31](https://github.com/ipfs-shipyard/service-worker-gateway/pull/31). @PedroMiguelSS already test this in `js.ipfs.io` and it seems everything working properly. Once the next deploy occurs it will be using the latest version of `js-ipfs`.

About the repo size, I went through the code, and it seems that `jsipfs repo stat` command leads to a `no limit` size, as you can see [js-ipfs-repo/src/index.js#L281](https://github.com/ipfs/js-ipfs-repo/blob/master/src/index.js#L281). @daviddias  Should I remove that part and maintain only the repo size?

Finally, regarding the list of `CIDs` that's a result of firefox using a specific process per tab (for service workers), instead of using its own like chrome and safari. I have an initial implementation for solving this issue, but I did not finish it yet. I am trying to use `indexDB` for storing that data across all the tabs, but then I was having problems with atomic operations between tabs. I will try to finish it during this week.

**Comment by daviddias** [comment]
> About the repo size, I went through the code, and it seems that jsipfs repo stat command leads to a no limit size, as you can see js-ipfs-repo/src/index.js#L281. @daviddias Should I remove that part and maintain only the repo size?

Got it. The UI is what is kind of weird. First the way that the numbers are displayed is super non informative and second If such limit is passed (or lack of thereof), better say not defined than 8PB
